[package]
name = "lcd"
version.workspace = true
edition.workspace = true

[dependencies]
esp-idf-sys.workspace = true
esp-idf-hal.workspace = true
anyhow.workspace = true
fastrand = "2.0.0"
shared = { path = "../../shared" }
lcd-lcm1602-i2c = "0.1.0"

[build-dependencies]
embuild.workspace = true
