[package]
name = "motor-driver"
version.workspace = true
edition.workspace = true

[dependencies]
esp-idf-sys = { version = "0.33", features = ["native", "binstart"] }
esp-idf-hal = "0.41.2"
anyhow = "1.0.75"
esp32-nimble = "0.2.2"

[build-dependencies]
embuild.workspace = true
